# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: lnkshrt
    networks:
      - lnkshrt-net
  rest:
    build: .
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - lnkshrt-net

networks:
  lnkshrt-net:
