name: ESLint check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install modules
        run: npm install

      - name: Run ESLint
        run: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
